apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue
  labels:
    service: redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-queue
  template:
    metadata:
      labels:
        service: redis-queue
    spec:
      containers:
        - name: redis-queue
          image: redis:6.0.8-buster
          args:
            - "--port"
            - "6379"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-queue
spec:
  selector:
    service: redis-queue
  ports:
    - port: 6379
      targetPort: 6379
