apiVersion: v1
kind: PersistentVolume
metadata:
  name: torch-cache-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/.cache/torch/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torch-cache-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
