apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      initContainers:
        - name: init-redis-queue
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup redis-queue; do sleep 2; done"]
      containers:
        - name: web
          image: mtrqq/icy-web:1.0.0
          env:
            - name: REDIS_HOST
              value: redis-queue
            - name: REDIS_PORT
              value: "6379"
            - name: FLASK_PORT
              value: "8080"
            - name: FLASK_ENV
              value: production
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    service: web
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
